### PR TITLE
Bump prometheus galaxy collection

### PR DESCRIPTION
**Pull request by thalesmg**
So that it supports ansible 2.17.*

https://github.com/prometheus-community/ansible/pull/414

### CODE REVIEW

**Review by id — APPROVED** [review]

**Comment by id** [comment]
`¯\_(ツ)_/¯`

```
ansible-galaxy collection install -r ansible/requirements.yml --force
Starting galaxy collection install process
Process install dependency map
Starting collection install process
Downloading https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/community-docker-3.10.3.tar.gz to /Users/id/.ansible/tmp/ansible-local-38534mmcu9ol5/tmpe5q2b00i/community-docker-3.10.3-c40zhmuk
Installing 'community.docker:3.10.3' to '/Users/id/.ansible/collections/ansible_collections/community/docker'
Downloading https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/prometheus-prometheus-0.16.3.tar.gz to /Users/id/.ansible/tmp/ansible-local-38534mmcu9ol5/tmpe5q2b00i/prometheus-prometheus-0.16.3-6t_t9cpw
community.docker:3.10.3 was installed successfully
'community.library_inventory_filtering_v1:1.0.1' is already installed, skipping.
Installing 'prometheus.prometheus:0.16.3' to '/Users/id/.ansible/collections/ansible_collections/prometheus/prometheus'
prometheus.prometheus:0.16.3 was installed successfully
'community.general:8.0.2' is already installed, skipping.
```

```
ansible --version
ansible [core 2.15.6]
  config file = /Users/id/work/tf-emqx-performance-test/ansible.cfg
  configured module search path = ['/Users/id/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/id/.asdf/installs/python/3.11.6/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/id/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/id/.asdf/installs/python/3.11.6/bin/ansible
  python version = 3.11.6 (main, Nov 19 2023, 20:34:04) [Clang 15.0.0 (clang-1500.0.40.1)] (/Users/id/.asdf/installs/python/3.11.6/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
```

**Comment by id** [comment]
0.19.0 was installed without warnings on my machine, ansible 2.17.4

**Comment by thalesmg** [comment]
> weird, 0.19.0 was installed without warnings on my machine, ansible 2.17.4

strange that 0.16.3 doesn't seem to log either

I tried reinstalling with `--force` too, didn't get any warnings

only when I did `terraform apply ...` it printed that :thinking:

**Comment by id** [comment]
May be when terraform executes ansible it resolves it to different package installed by different python? I.e., if you use venv or asdf, terraform probably does not make use of it.

**Pull request merged**
